### PR TITLE
Use suggestions of David

### PR DESCRIPTION
**Pull request by mayer79**
Added suggestions in https://github.com/mayer79/kernelshap/pull/18, fixed imports, example, news etc.

Solves https://github.com/mayer79/kernelshap/issues/17

### CODE REVIEW

**Comment by mayer79** [comment]
@dswatson: would be fantastic if you could have a look at the changes. I was unable to directly pull your main branch due to different reasons, including my own inability ;)

**Comment by mayer79** [comment]
Going through the examples in the Readme, I get errors for

- ranger
- gam
- keras (which is quite acceptable)

The gam error is a bit ugly...

**Comment by dswatson** [comment]
That's weird, it looks like I can run the `ranger` and `gam` code chunks without any problem using this branch. (`keras` leads to memory issues on my machine, so I can't evaluate it for now.) Can you post your error messages?

**Comment by mayer79** [comment]
Sweet! Using forked processes (the thing that is not possible on Windows) seems to be much more reliable compared to running multiple R sessions in parallel...

The error messages are as if the model package ("ranger" or "mgcv") is not loaded. If I set 
```
foreach::foreach(i = seq_len(n), .packages = c("mgcv", "ranger"))
```
everything is okay.

**Comment by dswatson** [comment]
Ahh ok, makes sense. Yet more finicky parallelization behavior.

**Comment by mayer79** [comment]
We could add arguments `foreach_packages` and `foreach_export` to deal with this, or even a named list `foreach_args`. And I will try to make a small example and report to "doFuture".

**Pull request merged**
